[package]
name = "ark-downloader"
version = "0.1.0"
authors = ["Kirill Taran <kirill.t256@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1"
evmap = "7.1.1"
either = "1.5.3"
seahash = "3.0.6"

clap = "3.0.0-beta.1"
